services:
  postgres:
    image: postgres:latest
    container_name: investeasy_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passer
      POSTGRES_DB: investeasy
      POSTGRES_USER: investeasy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - investeasy_network

  adminer:
    image: adminer
    container_name: investeasy_adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - investeasy_network

volumes:
  postgres_data:
    driver: local

networks:
  investeasy_network:
    driver: bridge